###
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name get-videos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--WebAppBoundary--

###

# @name create-transcription
POST http://localhost:3333/videos/584e160d-bccb-414a-b978-e2b1e066ae4d/transcription
Content-Type: application/json

{
  "prompt": "pix"
}
###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "584e160d-bccb-414a-b978-e2b1e066ae4d",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
###