###
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name get-videos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--WebAppBoundary--

# @name get-videos